Repository AY2324S2-CS2103T-W10-2/tp, pull requests merged in 2024-04, with the labels that each got.

#187 Fix intro link
  docs/UserGuide.md
Labels: type.Bug

#188 Fix ug pic bug
  docs/images/ug-images/BasicGuiNavigation.png
  docs/images/ug-images/PersonCardGuiNavigation.png
Labels: type.Bug, priority.High

#189 Add more help commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High

#191 Improve code quality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditMaintainerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditSupplierCommandParserTest.java
Labels: type.Bug, priority.High

#192 Add logging assertions
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.Medium

#199 Update UG
  docs/UserGuide.md
Labels: priority.High

#198 Standardise exception handling
  docs/UserGuide.md
  src/main/java/seedu/address/logic/messages/NoteMessages.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
Labels: type.Task, priority.High

#200 Further dg update help remind note
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/HelpCommandSequenceDiagram.puml
  docs/diagrams/NoteCommandSequenceDiagram.puml
  docs/diagrams/RemindCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/HelpCommandSequenceDiagram.png
  docs/images/NoteCommandSequenceDiagram.png
  docs/images/RemindCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#203 Update list
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.Task

#207 Update dg note remind help
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/NoteCommandSequenceDiagram.puml
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/NoteCommandSequenceDiagram.png
Labels: type.Task, priority.High

#204 Update dg branch
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/PinCommandSequenceDiagram.puml
  docs/diagrams/UnpinCommandSequenceDiagram.puml
  docs/images/EditCommandSequenceDiagram.png
  docs/images/PinCommandSequenceDiagram.png
  docs/images/UnpinCommandSequenceDiagram.png
Labels: type.Task, priority.High

#208 Update ug specific instructions
  docs/UserGuide.md
Labels: type.Task, priority.High

#213 Update UG Screenshots
  docs/UserGuide.md
  docs/images/ug-images/command-images/add-after.png
  docs/images/ug-images/command-images/add-before.png
  docs/images/ug-images/command-images/addcommand.png
  docs/images/ug-images/command-images/beforeundocommand.png
  docs/images/ug-images/command-images/deadlinecommand.png
  docs/images/ug-images/command-images/delete-after.png
  docs/images/ug-images/command-images/delete-before.png
  docs/images/ug-images/command-images/deletecommand.png
  docs/images/ug-images/command-images/edit-after.png
  docs/images/ug-images/command-images/edit-before.png
  docs/images/ug-images/command-images/editcommand.png
  docs/images/ug-images/command-images/help-after.png
  docs/images/ug-images/command-images/help-before.png
  docs/images/ug-images/command-images/helpcommand.png
  docs/images/ug-images/command-images/listcommand.png
  docs/images/ug-images/command-images/note-after.png
  docs/images/ug-images/command-images/note-before.png
  docs/images/ug-images/command-images/notecommand.png
  docs/images/ug-images/command-images/pin-after.png
  docs/images/ug-images/command-images/pin-before.png
  docs/images/ug-images/command-images/pincommand.png
  docs/images/ug-images/command-images/rate-after.png
  docs/images/ug-images/command-images/rate-before.png
  docs/images/ug-images/command-images/ratecommand.png
  docs/images/ug-images/command-images/redo-after.png
  docs/images/ug-images/command-images/redo-before.png
  docs/images/ug-images/command-images/redocommand.png
  docs/images/ug-images/command-images/remindcommand.png
  docs/images/ug-images/command-images/search-after.png
  docs/images/ug-images/command-images/search-before.png
  docs/images/ug-images/command-images/searchcommand.png
  docs/images/ug-images/command-images/sort-after.png
  docs/images/ug-images/command-images/sort-before.png
  docs/images/ug-images/command-images/sortcommand.png
  docs/images/ug-images/command-images/undo-after.png
  docs/images/ug-images/command-images/undo-before.png
  docs/images/ug-images/command-images/undocommand.png
  docs/images/ug-images/command-images/unpin-after.png
  docs/images/ug-images/command-images/unpin-before.png
  docs/images/ug-images/command-images/unpincommand.png
Labels: type.Task, priority.High

#214 Fix remind bug
  src/main/java/seedu/address/model/person/RemindPredicate.java
Labels: type.Bug, priority.High

#218 Update ug exceptions
  docs/UserGuide.md
  docs/images/ug-images/command-images/clearcommand.png
  docs/images/ug-images/error-images/invalidField.png
  docs/images/ug-images/error-images/unknownCommand.png
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, priority.Medium

#224 Update navigating gui
  docs/images/ug-images/BasicGuiNavigation.png
  docs/images/ug-images/PersonCardGuiNavigation.png
Labels: type.Task, priority.High

#225 Fix edit bug 2
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#227 Update dg
  docs/DeveloperGuide.md
Labels: type.Task

#229 Minor update
  src/main/java/seedu/address/logic/messages/RedoMessages.java
  src/main/java/seedu/address/logic/messages/UndoMessages.java
Labels: type.Task, priority.High

#296 Fix minor bugs
  docs/DeveloperGuide.md
  docs/team/chiageng.md
  docs/team/jamessinmaojun.md
  docs/team/jannaleong.md
  docs/team/joshy837.md
  docs/team/yleeyilin.md
  src/main/java/seedu/address/logic/messages/EditMessages.java
Labels: type.Task, priority.High

#299 Improve testing and quality
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/logic/messages/NoteMessages.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/ui/HelpOtherWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/person/DeadlineNoteTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.Medium

#300 Fix pin edit bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
Labels: type.Bug, priority.High

#304 Improve code quality
  src/main/java/seedu/address/logic/messages/EditMessages.java
  src/main/java/seedu/address/logic/messages/PinMessages.java
  src/main/java/seedu/address/logic/messages/RateMessages.java
  src/main/java/seedu/address/logic/messages/UnpinMessages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
  src/test/java/seedu/address/logic/parser/PinCommandParserTest.java
Labels: type.Bug, priority.High

#305 Update code quality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/PinCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task

#306 Fix code quality
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
Labels: type.Task, priority.High

#308 Add specfics to ug
  docs/UserGuide.md
  docs/images/ug-images/command-images/deletecommand.png
  docs/images/ug-images/command-images/helpcommand.png
  docs/images/ug-images/error-images/invalidField.png
  docs/images/ug-images/error-images/missingField.png
  docs/images/ug-images/error-images/unknownCommand.png
Labels: type.Task, priority.High

#313 Update code quality help note
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DeadlineNote.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/RemindPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DeadlineNoteTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/RemindPredicateTest.java
Labels: type.Task, priority.Medium

#314 Fix UG errors
  docs/UserGuide.md
Labels: type.Task, priority.High

#316 Check DG
  docs/DeveloperGuide.md
Labels: priority.High

#318 Correct dg
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#319 Improve ug
  docs/UserGuide.md
Labels: type.Bug, priority.High

#322 Update ug images
  docs/UserGuide.md
  docs/images/ug-images/BasicGuiNavigation.png
  docs/images/ug-images/PersonCardGuiNavigation.png
  docs/images/ug-images/command-images/addcommand.png
  docs/images/ug-images/command-images/beforeundocommand.png
  docs/images/ug-images/command-images/clearcommand.png
  docs/images/ug-images/command-images/deadlinecommand.png
  docs/images/ug-images/command-images/deletecommand.png
  docs/images/ug-images/command-images/editcommand.png
  docs/images/ug-images/command-images/helpcommand.png
  docs/images/ug-images/command-images/listcommand.png
  docs/images/ug-images/command-images/notecommand.png
  docs/images/ug-images/command-images/pincommand.png
  docs/images/ug-images/command-images/ratecommand.png
  docs/images/ug-images/command-images/redocommand.png
  docs/images/ug-images/command-images/remindcommand.png
  docs/images/ug-images/command-images/searchcommand.png
  docs/images/ug-images/command-images/sortcommand.png
  docs/images/ug-images/command-images/undocommand.png
  docs/images/ug-images/command-images/unpincommand.png
  docs/images/ug-images/error-images/invalidField.png
  docs/images/ug-images/error-images/unknownCommand.png
Labels: type.Task, priority.High

#325 Update ug code
  docs/UserGuide.md
  docs/images/ug-images/error-images/missingField.png
Labels: type.Task, priority.High

#330 Update reposense
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/logic/messages/NoteMessages.java
  src/main/java/seedu/address/logic/messages/RemindMessages.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DeadlineNote.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RemindPredicate.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High

#333 Add help test case
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#336 Update group ug reposense
  docs/UserGuide.md
  docs/team/jannaleong.md
Labels: type.Task, priority.High
