Repository AY2324S2-CS2103T-W10-2/tp, pull requests merged in 2024-03, with the labels that each got.

#34 Update AboutUs, User Guides and Developer Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/chiageng.png
  docs/team/chiageng.md
Labels: type.Task

#31 Update AboutUs.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/images/jamessinmaojun.png
  docs/team/jamessinmaojun.md
Labels: type.Task

#42 Add more user stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#76 Fix edit command bugs
  docs/UserGuide.md
  docs/team/yleeyilin.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditMaintainerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditSupplierCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug, severity.Medium

#77 Update Ui Class Uml
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.Medium

#86 Improve edit code quality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
Labels: type.Task

#83 Add note command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.Medium

#107 Expand note to all classes
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#115 Edit help command structure
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HelpDeleteCommand.java
  src/main/java/seedu/address/logic/commands/HelpEditCommand.java
  src/main/java/seedu/address/logic/commands/HelpPoochMaintenanceCommand.java
  src/main/java/seedu/address/logic/commands/HelpPoochStaffCommand.java
  src/main/java/seedu/address/logic/commands/HelpPoochSupplierCommand.java
  src/main/java/seedu/address/logic/commands/HelpSearchCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/HelpAddWindow.java
  src/main/java/seedu/address/ui/HelpPoochStaffWindow.java
  src/main/java/seedu/address/ui/HelpPoochSupplierWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpEditCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpPoochMaintenanceCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpPoochStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpPoochSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpSearchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: type.Task, priority.Medium

#119 Fix note person class bug
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
Labels: type.Bug, priority.High

#121 Fix Note test cases
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
Labels: type.Bug, priority.High

#120 Fix edit filter bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/messages/AddMessages.java
  src/main/java/seedu/address/logic/messages/DeleteMessages.java
  src/main/java/seedu/address/logic/messages/EditMessages.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSupplierCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/HelpEditWindow.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMaintainerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMaintainerCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditMaintainerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditSupplierCommandParserTest.java
  src/test/java/seedu/address/logic/stubs/ModelStub.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#122 Update UG for Help and Note command
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#129 Update UG for search and sort command
  docs/UserGuide.md
Labels: type.Task

#134 Add navigating gui
  bin/test/seedu/address/testutil/EditSupplierDescriptorBuilder.class
  docs/UserGuide.md
  docs/images/ug-images/basicGuiNavigation.png
  docs/images/ug-images/personCardGuiNavigation.png
Labels: type.Task, priority.High

#136 Add UG Useful Notations and Glossary
  docs/UserGuide.md
Labels: type.Task

#137 Update UG Features Formatting
  docs/UserGuide.md
Labels: priority.High

#128 Add Pin and Unpin command
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/logic/messages/PinMessages.java
  src/main/java/seedu/address/logic/messages/UnpinMessages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpinCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Pin.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/PinCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PinCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnpinCommandParserTest.java
  src/test/java/seedu/address/logic/stubs/ModelStub.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PinTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.Medium

#127 Update DG for Delete and Rate Commands
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditMaintainerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditSupplierCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/messages/RateMessages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMaintainerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/seedu/address/model/person/MaintainerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StaffTest.java
  src/test/java/seedu/address/model/person/SupplierTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/MaintainerBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
  src/test/java/seedu/address/testutil/SupplierBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#143 Update dg help remind note
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#125 Update DG for Edit and Pin command
  docs/DeveloperGuide.md
Labels: type.Task

#162 Update command format
  docs/UserGuide.md
Labels: type.Task, priority.High

#163 Branch update UG QNA
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Task

#164 Update product description
  docs/UserGuide.md
Labels: type.Task

#165 Enhance add edit
  docs/UserGuide.md
Labels: type.Task

#177 Fix note exception bugs
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/messages/NoteMessages.java
  src/main/java/seedu/address/logic/messages/RemindMessages.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DeadlineNote.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/person/DeadlineNoteTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#182 Update UG intro
  docs/UserGuide.md
Labels: type.Task

#184 Update ug command desc
  docs/UserGuide.md
  docs/images/ug-images/basicGuiNavigation.png
  docs/images/ug-images/personCardGuiNavigation.png
Labels: type.Task, priority.High

#183 Fix pin bug
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/model/person/Maintainer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Bug, priority.High

#185 Improve code quality of help/remind/note
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/messages/HelpMessages.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/DeadlineNote.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/ui/HelpDeleteWindow.java
  src/main/java/seedu/address/ui/HelpEditWindow.java
  src/main/java/seedu/address/ui/HelpOtherWindow.java
  src/main/java/seedu/address/ui/HelpSearchWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High
